spring.datasource.url=jdbc:postgresql://localhost:5432/cloudstorage
spring.datasource.username=postgres
spring.datasource.password=Postgree123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

cloudinary.cloudName=zqgnzqxx
cloudinary.apiKey=839864985367276
cloudinary.apiSecret=Hu5IVdDr-Oaa5hC-6Et5JbxB8dg